sudo: false
language: ruby
cache: bundler

rvm:
  - 2.5

before_install:
  - curl -sL https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip > terraform.zip
  - unzip terraform.zip

script: bundle exec rspec spec
