# The short name of your organization
#
org:

# The email address for receiving ops related alert emails
#
ops_email:

# The global name prefix for disambiguating resource names that have a global
# scope (e.g. s3 bucket names)
#
global_name_prefix: "#{org}-#{atmos_env}-"

# The local name prefix for disambiguating resource names that have a local
# scope (e.g. when running multiple environments in the same account)
#
local_name_prefix:

# The recipes to use for all environments, override at environment level if
# need be.  The recipes to use when bootstrapping each environment will be
# under the bootstrap key.  These are kept separate to make it easy to tear
# down an environment without breaking terraform mid-destroy.  Most new
# deployments will have all recipes under a single key (Default), but the use
# of multiple keys to segment your infrastructure is useful as it grows larger
#
recipes:
  bootstrap:
  default:

# Environment specific overrides.  When adding new environments place them
# after the existing ones so that you don't end up with permission issues when
# bootstrapping the new account
#
environments:
  ops:
    account_id:

# Sources for atmos templates
#
template_sources:
- name: atmos-recipes
  location: git@github.com:/simplygenius/atmos-recipes.git
#  - name: atmos-pro-recipes
#    location: git@github.com:simplygenius/atmos-pro-recipes.git
